### ISSUE TITLE
Max number of iteration reached for pairwise_align()

### ISSUE THREAD

**Issue by aaadc** [raphael-group/paste#27]
I always got this warning when using pairwise_align() and I got the same warning when setting pi12 = pst.pairwise_align(slice1, slice2,numItermax=1000000)
and my two consecutive slices were very poorly aligned, Is that the problem?

RESULT MIGHT BE INACURATE
Max number of iteration reached, currently 100000. Sometimes iterations go on in cycle even though the solution has been reached, to check if it's the case here have a look at the minimal reduced cost. If it is very close to machine precision, you might actually have the correct solution, if not try setting the maximum number of iterations a bit higher

**Comment by mrland99** [comment]
Hi,

A poor alignment is most likely not due to the max number of iterations. The POT solver is likely getting stuck at a local minima. I would recommend trying to vary levels of alpha (e.g. `alpha = 0.1, 0.01, 0.001).

Are your spatial slices slightly symmetric by chance? Intuitively, the more symmetric the shape of the tissue the harder it is to find the optimal rotation based solely spatial information. For example, if the spots between layers formed a perfect square and you were only looking at spatial coordinates, you'd have no idea which 90 degree rotation would give the optimal rotation. This is also why in the case above you could see better results at lower alpha (giving more weight to gene expression).

In situations like these, if you know the proper orientation (to some degree), another option would be to try roughly rotating the spatial coordinates yourself before running PASTE.
